### ISSUE TITLE
More Support <3

### ISSUE THREAD

**Issue by ghost** [SpaicyGaming/ChunkMiner#3]
The plugin supports the UUID version,

Any way you can make this work with https://www.spigotmc.org/resources/factions.1900/ & https://www.spigotmc.org/resources/massivecore.1901/

It would be awesome if it did.

Why: I would like using this plugin but converting onto FactionUUID is a no for me.

**Comment by michelecoco** [comment]
I'm sorry, I will not add Massivecore's Factions support.
FactionsUUID has a great support and way more features. There are no reasons to keep using Massivecore's Factions.
